# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stable-diffusion-from-scratch',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/stable-diffusion-from-scratch',
                'lib_path': 'foundation'},
  'syms': { 'foundation.core': { 'foundation.core.A': ('core.html#a', 'foundation/core.py'),
                                 'foundation.core.A.__init__': ('core.html#a.__init__', 'foundation/core.py'),
                                 'foundation.core.B': ('core.html#b', 'foundation/core.py'),
                                 'foundation.core.B.__init__': ('core.html#b.__init__', 'foundation/core.py'),
                                 'foundation.core.foo': ('core.html#foo', 'foundation/core.py')},
            'foundation.transformer.attention': { 'foundation.transformer.attention.A': ( 'transformer.attention.html#a',
                                                                                          'foundation/transformer/attention.py'),
                                                  'foundation.transformer.attention.MultiHeadAttention': ( 'transformer.attention.html#multiheadattention',
                                                                                                           'foundation/transformer/attention.py'),
                                                  'foundation.transformer.attention.MultiHeadAttention.__init__': ( 'transformer.attention.html#multiheadattention.__init__',
                                                                                                                    'foundation/transformer/attention.py')}}}
