# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'A', 'B']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 9
@docs
class A(nn.Module):
    def __init__(self):
        super().__init__()
      
    _docs = dict(cls_doc="xxx")

# %% ../nbs/00_core.ipynb 10
class B(nn.Module):
    # A simple comment preceding a simple print statement
    def __init__(self):
        super().__init__()
