# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_diffusion.ipynb.

# %% auto 0
__all__ = ['device', 'corrupt']

# %% ../nbs/10_diffusion.ipynb 4
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from diffusers import DDPMScheduler, UNet2DModel
from matplotlib import pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f'Using device: {device}')

# %% ../nbs/10_diffusion.ipynb 16
def corrupt(img, amount):
    noise = torch.randn_like(img)
    return (1-amount)*img + noise * amount
