# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_utils.ipynb.

# %% auto 0
__all__ = ['show_img']

# %% ../nbs/99_utils.ipynb 4
from matplotlib import pyplot as plt

# %% ../nbs/99_utils.ipynb 6
def show_img(img):
    return plt.imshow(img, cmap='Greys');
