project:
  type: website

format:
  html:
    theme: cosmo
    css:
        - styles.css
        - hint.css
        - tips.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]