# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stable-diffusion-from-scratch',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/stable-diffusion-from-scratch',
                'lib_path': 'stable_diffusion_from_scratch'},
  'syms': { 'stable_diffusion_from_scratch.core': { 'stable_diffusion_from_scratch.core.foo': ( 'core.html#foo',
                                                                                                'stable_diffusion_from_scratch/core.py')}}}
